CREATE TABLE IF NOT EXISTS Note (
  `IdNote` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `Titre` VARCHAR(50) NOT NULL,
  `Contenu` TEXT NOT NULL,
   PRIMARY KEY (IdNote)
);

/* Dictionnaire de données pour la classe GenericDao */
CREATE TABLE IF NOT EXISTS Dictionnaire (
  `TABLE_NAME` VARCHAR(25) NOT NULL,
  `COLUMN_NAME` VARCHAR(25) NOT NULL,
  `IS_ID_COL` BOOLEAN NOT NULL,
  `DATA_TYPE` TEXT NOT NULL,
  `DATA_PARAMS` TEXT DEFAULT NULL,
  `FK_LINK` TEXT DEFAULT NULL,
  PRIMARY KEY (TABLE_NAME, COLUMN_NAME)
);

INSERT INTO Dictionnaire (TABLE_NAME, COLUMN_NAME, IS_ID_COL, DATA_TYPE, DATA_PARAMS, FK_LINK)
VALUES ('Note', 'IdNote', TRUE, 'int', NULL, NULL);
INSERT INTO Dictionnaire (TABLE_NAME, COLUMN_NAME, IS_ID_COL, DATA_TYPE, DATA_PARAMS, FK_LINK)
VALUES ('Note', 'Titre', FALSE, 'string', NULL, NULL);
INSERT INTO Dictionnaire (TABLE_NAME, COLUMN_NAME, IS_ID_COL, DATA_TYPE, DATA_PARAMS, FK_LINK)
VALUES ('Note', 'Contenu', FALSE, 'string', NULL, NULL);